Unit and integration tests
Kyrsor/demo pull request #3
Opened 2021-01-26 06:37 UTC by Kyrsor

2021-01-26 07:53 UTC, alexk-itechart requested changes
Good start on the tests. Integration tests are fine, though I would add more cases to cover. Also, you can look at the RESTAssured library for testing endpoints, sometimes it's what is used for integration tests.
As for unit tests, for some of them, it's not clear what is being verified. And similar to integration tests more cases can be covered here.

2021-01-26 07:53 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/controller/DistanceRestControllerIntegrationTest.java
> +public class DistanceRestControllerIntegrationTest {
I would add more test cases here. Like checking that endpoint can't save the same distance, to check the case when start and end cities are identical, etc.

2021-01-26 07:53 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/service/impl/DistanceServiceImplTest.java
> +        //then
I don't see what we're checking here. The first 2 tests expect exceptions, so not doing asserts is okay there. Here it's not clear what you're verifying. Using mockito you can check that a specific method was called and a lot of other stuff. Also, usually, you would check the returned value from as service method.

2021-01-26 07:53 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/service/impl/DistanceServiceImplTest.java
> +    public void buildRoutesServiceExceptionNoStartCity() {
How about a not-existing finish city?

2021-01-26 07:53 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/service/impl/DistanceServiceImplTest.java
> +    public void buildRoutes() {
What will happen when there's no route between cities? Consider this situation - you have distances A->B and C->D (exact numbers are not important), and you'd like to find the distance between A and D. Formally, all your checks should be fine, but the route does not exist for them.

2021-01-26 12:24 UTC, alexk-itechart requested changes
You're still not checking the most valuable part of the service - what it returns. Save the value that service returns and check if it's what you'd expect.

2021-01-26 12:24 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/controller/DistanceRestControllerIntegrationTest.java
> +           .andExpect(status().isBadRequest());
Is it reasonable to give 400 error to a user when no route is found? Will 404 serve a better purpose for that?

2021-01-26 12:47 UTC, Kyrsor commented on src/test/java/com/itechart/demo/controller/DistanceRestControllerIntegrationTest.java
> +           .andExpect(status().isBadRequest());
Should I remake serviceException so that it returns 404? Now 400 is written in ExceptionHandler

2021-01-26 12:51 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/controller/DistanceRestControllerIntegrationTest.java
> +           .andExpect(status().isBadRequest());
This way you will return 404 for any ServiceException thrown, which will be incorrect. You can either create a new exception that will serve this purpose or modify the service exception in a way to provide some error code and use this code in the exception handler to determine what HTTP code to return.

2021-01-27 06:23 UTC, alexk-itechart reviewed
That looks good now. Although, I noticed that the positive tests for finding routes could be extended. In your test, you verify the simplest case possible - find the distance you created. What would be better is to check that the service could find 2 or more routes for a specified route that contains 3 or more distances.

2021-01-27 09:08 UTC, Kyrsor commented on src/test/java/com/itechart/demo/service/impl/DistanceServiceImplTest.java
> +        when(distanceRepository.findAllByCity(startCity)).thenReturn(distances);
234 line sholud return not empty list to avoid exception, it is not necessary for them to be different

2021-01-27 09:11 UTC, alexk-itechart commented on src/test/java/com/itechart/demo/service/impl/DistanceServiceImplTest.java
> +        when(distanceRepository.findAllByCity(startCity)).thenReturn(distances);
yeah, this is understood. However, you return the exact same list both times, regardless of the city passed. While in the test it's not breaking anything, it's not what repository would return.

2021-01-27 09:22 UTC, alexk-itechart approved these changes

2021-01-27 09:23 UTC, merged